#!/usr/bin/env bash
#prints "Best School" 10 times and "Hi" at nineth time

count=0
while [ $count -lt 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    (( count++ ))
done
