#!/usr/bin/env bash
#prints "bad luch" for 4, "good luck" for 8 and "best luch" for the rest

count=1
while [ $count -le 10 ]
do
    if [ $count -eq 4 ]
    then
        echo "bad luck"
    elif [ $count -eq 8 ]
    then
        echo "good luck"
    else
    echo "Best School"
    fi
    (( count++ ))
done
